#WIP

version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      DB_URL: "mssql+pyodbc://SA:Password123*@172.18.0.1:1433/voka?driver=ODBC+Driver+17+for+SQL+Server"
