version: "3.8"
services:
  sqlserver:
    container_name: sqlserver-db
    image: sqlserver-image
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123*"
      ACCEPT_EULA: "Y"

# Run: docker-compose up -d
# Stop: docker-compose down

# Sources: 
# https://blog.logrocket.com/docker-sql-server/